name: myenv
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - alabaster=0.7.16
  - arrow=1.4.0
  - astroid=3.3.11
  - asttokens=3.0.0
  - async-timeout=5.0.1
  - asyncssh=2.21.1
  - atomicwrites=1.4.0
  - attrs=25.4.0
  - autopep8=2.0.4
  - babel=2.16.0
  - backports.tarfile=1.2.0
  - bcrypt=5.0.0
  - beautifulsoup4=4.13.5
  - binaryornot=0.4.4
  - black=25.9.0
  - blas=1.0
  - bleach=6.2.0
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.4
  - cattrs=25.3.0
  - certifi=2025.11.12
  - cffi=2.0.0
  - chardet=5.2.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.3
  - cookiecutter=2.6.0
  - cryptography=46.0.3
  - cuda-cccl=12.4.127
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.4.127
  - cuda-runtime=11.8.0
  - cudatoolkit=11.8.0
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.4.0
  - docstring-to-markdown=0.17
  - docutils=0.21.2
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.3
  - filelock=3.20.0
  - flake8=7.1.1
  - freetype=2.13.3
  - frozenlist=1.8.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - icu=73.1
  - idna=3.11
  - imagesize=1.4.1
  - importlib-metadata=8.5.0
  - inflection=0.5.1
  - intel-openmp=2023.1.0
  - intervaltree=3.1.0
  - ipykernel=6.31.0
  - ipython=8.30.0
  - ipython_pygments_lexers=1.1.1
  - isort=6.1.0
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jedi=0.19.2
  - jellyfish=1.1.3
  - jinja2=3.1.6
  - jpeg=9f
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.9.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_pygments=0.3.0
  - keyring=25.7.0
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=3.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.5.147
  - libcurand-dev=10.3.5.147
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libkrb5=1.21.3
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.50
  - libpq=17.6
  - libsodium=1.0.20
  - libspatialindex=1.9.3
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzlib=1.3.1
  - lsprotocol=2025.0.0
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.2.1
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mistune=3.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - more-itertools=10.8.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.7.0
  - mypy_extensions=1.0.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numpy=2.0.1
  - numpy-base=2.0.1
  - numpydoc=1.9.0
  - openjpeg=2.5.2
  - openssl=3.0.18
  - packaging=25.0
  - pandoc=3.8
  - pandocfilters=1.5.1
  - parso=0.8.5
  - pathspec=0.12.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.3
  - platformdirs=4.5.0
  - pluggy=1.5.0
  - ply=3.11
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycares=4.10.0
  - pycodestyle=2.12.1
  - pycparser=2.23
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygithub=2.8.1
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pylint=3.3.8
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.6.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.2
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-ruff=2.3.0
  - python-lsp-server=1.13.1
  - python-slugify=8.0.4
  - python-tzdata=2025.2
  - pytokens=0.2.0
  - pytoolconfig=1.2.6
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyuca=1.2
  - pywin32=311
  - pywin32-ctypes=0.2.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qdarkstyle=3.2.3
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.4.0
  - qtconsole=5.7.0
  - qtpy=2.4.3
  - referencing=0.37.0
  - requests=2.32.5
  - rich=14.2.0
  - rope=1.14.0
  - rpds-py=0.28.0
  - rtree=1.4.1
  - ruff=0.12.0
  - setuptools=80.9.0
  - sip=6.7.12
  - six=1.17.0
  - snowballstemmer=3.0.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=7.3.7
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=2.0.0
  - spyder=6.1.0
  - spyder-kernels=3.1.1
  - sqlite=3.51.0
  - stack_data=0.6.3
  - superqt=0.7.6
  - sympy=1.14.0
  - tbb=2021.8.0
  - text-unidecode=1.3
  - textdistance=4.6.3
  - three-merge=0.1.1
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.2.1
  - tomlkit=0.13.3
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - ujson=5.11.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - watchdog=6.0.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - whatthepatch=1.0.7
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - winloop=0.3.1
  - xz=5.6.4
  - yaml=0.2.5
  - yapf=0.43.0
  - yarl=1.22.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.60.1
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - pandas==2.3.3
      - patsy==1.0.2
      - pyparsing==3.2.5
      - pytz==2025.2
      - qstylizer==0.2.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - statsmodels==0.14.5
      - threadpoolctl==3.6.0
      - torchaudio==2.5.1
      - torchvision==0.20.1

